--[[----------------------------------------------------------------------------
This file was generated by FNF Sprite Merger Tool
------------------------------------------------------------------------------]]


local Pico_FNF_assetss = graphics.newSprite(
	love.graphics.newImage(graphics.imagePath("weekend1/char/Pico_FNF_assetss")),
	{
		{x = 938, y = 3530, width = 518, height = 490, offsetX = -125, offsetY = -87, offsetWidth = 1061, offsetHeight = 615}, -- 1: Pico Death Stab0001
		{x = 0, y = 3010, width = 563, height = 518, offsetX = -125, offsetY = -59, offsetWidth = 1061, offsetHeight = 615}, -- 2: Pico Death Stab0002
		{x = 2466, y = 3010, width = 548, height = 499, offsetX = -140, offsetY = -78, offsetWidth = 1061, offsetHeight = 615}, -- 3: Pico Death Stab0003
		{x = 5772, y = 2461, width = 563, height = 521, offsetX = -140, offsetY = -56, offsetWidth = 1061, offsetHeight = 615}, -- 4: Pico Death Stab0004
		{x = 1959, y = 2461, width = 563, height = 541, offsetX = -140, offsetY = -36, offsetWidth = 1061, offsetHeight = 615}, -- 5: Pico Death Stab0005
		{x = 4010, y = 1310, width = 576, height = 570, offsetX = -140, offsetY = -1, offsetWidth = 1061, offsetHeight = 615}, -- 6: Pico Death Stab0006
		{x = 4588, y = 1310, width = 570, height = 569, offsetX = -140, offsetY = -8, offsetWidth = 1061, offsetHeight = 615}, -- 7: Pico Death Stab0007
		{x = 672, y = 1891, width = 576, height = 563, offsetX = -140, offsetY = -14, offsetWidth = 1061, offsetHeight = 615}, -- 8: Pico Death Stab0008
		{x = 672, y = 1891, width = 576, height = 563, offsetX = -140, offsetY = -14, offsetWidth = 1061, offsetHeight = 615}, -- 9: Pico Death Stab0009
		{x = 4109, y = 1891, width = 552, height = 551, offsetX = -140, offsetY = -25, offsetWidth = 1061, offsetHeight = 615}, -- 10: Pico Death Stab0010
		{x = 4109, y = 1891, width = 552, height = 551, offsetX = -140, offsetY = -25, offsetWidth = 1061, offsetHeight = 615}, -- 11: Pico Death Stab0011
		{x = 4059, y = 3010, width = 566, height = 498, offsetX = -141, offsetY = -11, offsetWidth = 1061, offsetHeight = 615}, -- 12: Pico Death Stab0012
		{x = 4059, y = 3010, width = 566, height = 498, offsetX = -141, offsetY = -11, offsetWidth = 1061, offsetHeight = 615}, -- 13: Pico Death Stab0013
		{x = 4627, y = 3010, width = 554, height = 498, offsetX = -141, offsetY = -23, offsetWidth = 1061, offsetHeight = 615}, -- 14: Pico Death Stab0014
		{x = 4627, y = 3010, width = 554, height = 498, offsetX = -141, offsetY = -23, offsetWidth = 1061, offsetHeight = 615}, -- 15: Pico Death Stab0015
		{x = 3016, y = 3010, width = 526, height = 499, offsetX = -139, offsetY = -51, offsetWidth = 1061, offsetHeight = 615}, -- 16: Pico Death Stab0016
		{x = 3016, y = 3010, width = 526, height = 499, offsetX = -139, offsetY = -51, offsetWidth = 1061, offsetHeight = 615}, -- 17: Pico Death Stab0017
		{x = 3544, y = 3010, width = 513, height = 499, offsetX = -139, offsetY = -64, offsetWidth = 1061, offsetHeight = 615}, -- 18: Pico Death Stab0018
		{x = 565, y = 3010, width = 514, height = 502, offsetX = -142, offsetY = -64, offsetWidth = 1061, offsetHeight = 615}, -- 19: Pico Death Stab0019
		{x = 434, y = 3530, width = 502, height = 493, offsetX = -142, offsetY = -85, offsetWidth = 1061, offsetHeight = 615}, -- 20: Pico Death Stab0020
		{x = 5183, y = 3010, width = 522, height = 498, offsetX = -156, offsetY = -78, offsetWidth = 1061, offsetHeight = 615}, -- 21: Pico Death Stab0021
		{x = 0, y = 6815, width = 488, height = 367, offsetX = -263, offsetY = -190, offsetWidth = 1061, offsetHeight = 615}, -- 22: Pico Death Stab0022
		{x = 3990, y = 6383, width = 488, height = 416, offsetX = -263, offsetY = -190, offsetWidth = 1061, offsetHeight = 615}, -- 23: Pico Death Stab0023
		{x = 2499, y = 6383, width = 491, height = 419, offsetX = -260, offsetY = -187, offsetWidth = 1061, offsetHeight = 615}, -- 24: Pico Death Stab0024
		{x = 502, y = 6383, width = 491, height = 428, offsetX = -260, offsetY = -187, offsetWidth = 1061, offsetHeight = 615}, -- 25: Pico Death Stab0025
		{x = 0, y = 6383, width = 500, height = 430, offsetX = -251, offsetY = -185, offsetWidth = 1061, offsetHeight = 615}, -- 26: Pico Death Stab0026
		{x = 995, y = 6383, width = 500, height = 427, offsetX = -251, offsetY = -185, offsetWidth = 1061, offsetHeight = 615}, -- 27: Pico Death Stab0027
		{x = 4979, y = 6383, width = 497, height = 415, offsetX = -254, offsetY = -197, offsetWidth = 1061, offsetHeight = 615}, -- 28: Pico Death Stab0028
		{x = 4480, y = 6383, width = 497, height = 416, offsetX = -254, offsetY = -197, offsetWidth = 1061, offsetHeight = 615}, -- 29: Pico Death Stab0029
		{x = 2992, y = 6383, width = 497, height = 419, offsetX = -254, offsetY = -194, offsetWidth = 1061, offsetHeight = 615}, -- 30: Pico Death Stab0030
		{x = 3491, y = 6383, width = 497, height = 419, offsetX = -254, offsetY = -194, offsetWidth = 1061, offsetHeight = 615}, -- 31: Pico Death Stab0031
		{x = 3491, y = 6383, width = 497, height = 419, offsetX = -254, offsetY = -194, offsetWidth = 1061, offsetHeight = 615}, -- 32: Pico Death Stab0032
		{x = 5707, y = 3010, width = 590, height = 497, offsetX = -254, offsetY = -23, offsetWidth = 1061, offsetHeight = 615}, -- 33: Pico Death Stab0033
		{x = 3120, y = 698, width = 606, height = 599, offsetX = -250, offsetY = -14, offsetWidth = 1061, offsetHeight = 615}, -- 34: Pico Death Stab0034
		{x = 3120, y = 698, width = 606, height = 599, offsetX = -250, offsetY = -14, offsetWidth = 1061, offsetHeight = 615}, -- 35: Pico Death Stab0035
		{x = 1036, y = 698, width = 794, height = 606, offsetX = -136, offsetY = -7, offsetWidth = 1061, offsetHeight = 615}, -- 36: Pico Death Stab0036
		{x = 3374, y = 0, width = 800, height = 611, offsetX = -161, offsetY = -2, offsetWidth = 1061, offsetHeight = 615}, -- 37: Pico Death Stab0037
		{x = 4176, y = 0, width = 800, height = 611, offsetX = -161, offsetY = -2, offsetWidth = 1061, offsetHeight = 615}, -- 38: Pico Death Stab0038
		{x = 1536, y = 0, width = 917, height = 613, offsetX = -79, offsetY = 0, offsetWidth = 1061, offsetHeight = 615}, -- 39: Pico Death Stab0039
		{x = 2455, y = 0, width = 917, height = 613, offsetX = -79, offsetY = 0, offsetWidth = 1061, offsetHeight = 615}, -- 40: Pico Death Stab0040
		{x = 4978, y = 0, width = 1034, height = 610, offsetX = -15, offsetY = -3, offsetWidth = 1061, offsetHeight = 615}, -- 41: Pico Death Stab0041
		{x = 0, y = 698, width = 1034, height = 610, offsetX = -15, offsetY = -3, offsetWidth = 1061, offsetHeight = 615}, -- 42: Pico Death Stab0042
		{x = 3728, y = 698, width = 1057, height = 596, offsetX = -4, offsetY = -17, offsetWidth = 1061, offsetHeight = 615}, -- 43: Pico Death Stab0043
		{x = 4787, y = 698, width = 1057, height = 596, offsetX = -4, offsetY = -17, offsetWidth = 1061, offsetHeight = 615}, -- 44: Pico Death Stab0044
		{x = 0, y = 1310, width = 1061, height = 579, offsetX = 0, offsetY = -34, offsetWidth = 1061, offsetHeight = 615}, -- 45: Pico Death Stab0045
		{x = 1063, y = 1310, width = 1061, height = 579, offsetX = 0, offsetY = -34, offsetWidth = 1061, offsetHeight = 615}, -- 46: Pico Death Stab0046
		{x = 2126, y = 1310, width = 626, height = 572, offsetX = -254, offsetY = -41, offsetWidth = 1061, offsetHeight = 615}, -- 47: Pico Death Stab0047
		{x = 5160, y = 1310, width = 670, height = 568, offsetX = -254, offsetY = -45, offsetWidth = 1061, offsetHeight = 615}, -- 48: Pico Death Stab0048
		{x = 5832, y = 1310, width = 670, height = 568, offsetX = -254, offsetY = -45, offsetWidth = 1061, offsetHeight = 615}, -- 49: Pico Death Stab0049
		{x = 573, y = 2461, width = 691, height = 543, offsetX = -254, offsetY = -70, offsetWidth = 1061, offsetHeight = 615}, -- 50: Pico Death Stab0050
		{x = 1266, y = 2461, width = 691, height = 543, offsetX = -254, offsetY = -70, offsetWidth = 1061, offsetHeight = 615}, -- 51: Pico Death Stab0051
		{x = 2524, y = 2461, width = 562, height = 537, offsetX = -254, offsetY = -51, offsetWidth = 1061, offsetHeight = 615}, -- 52: Pico Death Stab0052
		{x = 5795, y = 1891, width = 562, height = 548, offsetX = -243, offsetY = -51, offsetWidth = 1061, offsetHeight = 615}, -- 53: Pico Death Stab0053
		{x = 2396, y = 1891, width = 571, height = 558, offsetX = -243, offsetY = -42, offsetWidth = 1061, offsetHeight = 615}, -- 54: Pico Death Stab0054
		{x = 0, y = 2461, width = 571, height = 547, offsetX = -254, offsetY = -42, offsetWidth = 1061, offsetHeight = 615}, -- 55: Pico Death Stab0055
		{x = 2969, y = 1891, width = 568, height = 556, offsetX = -254, offsetY = -45, offsetWidth = 1061, offsetHeight = 615}, -- 56: Pico Death Stab0056
		{x = 3539, y = 1891, width = 568, height = 556, offsetX = -254, offsetY = -45, offsetWidth = 1061, offsetHeight = 615}, -- 57: Pico Death Stab0057
		{x = 4663, y = 1891, width = 564, height = 551, offsetX = -254, offsetY = -62, offsetWidth = 1061, offsetHeight = 615}, -- 58: Pico Death Stab0058
		{x = 5229, y = 1891, width = 564, height = 551, offsetX = -254, offsetY = -62, offsetWidth = 1061, offsetHeight = 615}, -- 59: Pico Death Stab0059
		{x = 1250, y = 1891, width = 571, height = 559, offsetX = -254, offsetY = -54, offsetWidth = 1061, offsetHeight = 615}, -- 60: Pico Death Stab0060
		{x = 1823, y = 1891, width = 571, height = 559, offsetX = -254, offsetY = -54, offsetWidth = 1061, offsetHeight = 615}, -- 61: Pico Death Stab0061
		{x = 2754, y = 1310, width = 626, height = 572, offsetX = -254, offsetY = -41, offsetWidth = 1061, offsetHeight = 615}, -- 62: Pico Death Stab0062
		{x = 3382, y = 1310, width = 626, height = 572, offsetX = -254, offsetY = -41, offsetWidth = 1061, offsetHeight = 615}, -- 63: Pico Death Stab0063
		{x = 0, y = 1891, width = 670, height = 568, offsetX = -254, offsetY = -45, offsetWidth = 1061, offsetHeight = 615}, -- 64: Pico Death Stab0064
		{x = 5982, y = 6383, width = 723, height = 382, offsetX = -13, offsetY = -9, offsetWidth = 736, offsetHeight = 392}, -- 65: Pico Down Note0000
		{x = 5982, y = 6383, width = 723, height = 382, offsetX = -13, offsetY = -9, offsetWidth = 736, offsetHeight = 392}, -- 66: Pico Down Note0001
		{x = 5478, y = 6383, width = 502, height = 392, offsetX = 0, offsetY = 0, offsetWidth = 736, offsetHeight = 392}, -- 67: Pico Down Note0002
		{x = 5478, y = 6383, width = 502, height = 392, offsetX = 0, offsetY = 0, offsetWidth = 736, offsetHeight = 392}, -- 68: Pico Down Note0003
		{x = 5478, y = 6383, width = 502, height = 392, offsetX = 0, offsetY = 0, offsetWidth = 736, offsetHeight = 392}, -- 69: Pico Down Note0004
		{x = 5478, y = 6383, width = 502, height = 392, offsetX = 0, offsetY = 0, offsetWidth = 736, offsetHeight = 392}, -- 70: Pico Down Note0005
		{x = 5478, y = 6383, width = 502, height = 392, offsetX = 0, offsetY = 0, offsetWidth = 736, offsetHeight = 392}, -- 71: Pico Down Note0006
		{x = 5478, y = 6383, width = 502, height = 392, offsetX = 0, offsetY = 0, offsetWidth = 736, offsetHeight = 392}, -- 72: Pico Down Note0007
		{x = 5478, y = 6383, width = 502, height = 392, offsetX = 0, offsetY = 0, offsetWidth = 736, offsetHeight = 392}, -- 73: Pico Down Note0008
		{x = 5478, y = 6383, width = 502, height = 392, offsetX = 0, offsetY = 0, offsetWidth = 736, offsetHeight = 392}, -- 74: Pico Down Note0009
		{x = 5478, y = 6383, width = 502, height = 392, offsetX = 0, offsetY = 0, offsetWidth = 736, offsetHeight = 392}, -- 75: Pico Down Note0010
		{x = 5982, y = 6383, width = 723, height = 382, offsetX = -10, offsetY = -52, offsetWidth = 736, offsetHeight = 392}, -- 76: Pico Down Note MISS0000
		{x = 5288, y = 5928, width = 495, height = 432, offsetX = -2, offsetY = 0, offsetWidth = 733, offsetHeight = 434}, -- 77: Pico Down Note MISS0001
		{x = 5288, y = 5928, width = 495, height = 432, offsetX = -2, offsetY = 0, offsetWidth = 733, offsetHeight = 434}, -- 78: Pico Down Note MISS0002
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 79: Pico Down Note MISS0003
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 80: Pico Down Note MISS0004
		{x = 1998, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 81: Pico Down Note MISS0005
		{x = 1998, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 82: Pico Down Note MISS0006
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 83: Pico Down Note MISS0007
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 84: Pico Down Note MISS0008
		{x = 1998, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 85: Pico Down Note MISS0009
		{x = 1998, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 86: Pico Down Note MISS0010
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 87: Pico Down Note MISS0011
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 88: Pico Down Note MISS0012
		{x = 1998, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 89: Pico Down Note MISS0013
		{x = 1998, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 90: Pico Down Note MISS0014
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 91: Pico Down Note MISS0015
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 92: Pico Down Note MISS0016
		{x = 1998, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 93: Pico Down Note MISS0017
		{x = 1998, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 94: Pico Down Note MISS0018
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 95: Pico Down Note MISS0019
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 96: Pico Down Note MISS0020
		{x = 1998, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 97: Pico Down Note MISS0021
		{x = 1998, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 98: Pico Down Note MISS0022
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 99: Pico Down Note MISS0023
		{x = 1497, y = 6383, width = 499, height = 426, offsetX = 0, offsetY = -6, offsetWidth = 733, offsetHeight = 434}, -- 100: Pico Down Note MISS0024
		{x = 5488, y = 5457, width = 435, height = 461, offsetX = -18, offsetY = -13, offsetWidth = 453, offsetHeight = 475}, -- 101: Pico Idle Dance0000
		{x = 5488, y = 5457, width = 435, height = 461, offsetX = -18, offsetY = -13, offsetWidth = 453, offsetHeight = 475}, -- 102: Pico Idle Dance0001
		{x = 539, y = 5457, width = 442, height = 468, offsetX = -11, offsetY = -6, offsetWidth = 453, offsetHeight = 475}, -- 103: Pico Idle Dance0002
		{x = 539, y = 5457, width = 442, height = 468, offsetX = -11, offsetY = -6, offsetWidth = 453, offsetHeight = 475}, -- 104: Pico Idle Dance0003
		{x = 2640, y = 4981, width = 448, height = 469, offsetX = -1, offsetY = -6, offsetWidth = 453, offsetHeight = 475}, -- 105: Pico Idle Dance0004
		{x = 3090, y = 4981, width = 444, height = 469, offsetX = -1, offsetY = -6, offsetWidth = 453, offsetHeight = 475}, -- 106: Pico Idle Dance0005
		{x = 5350, y = 4504, width = 444, height = 474, offsetX = -1, offsetY = -1, offsetWidth = 453, offsetHeight = 475}, -- 107: Pico Idle Dance0006
		{x = 5796, y = 4504, width = 442, height = 474, offsetX = -1, offsetY = -1, offsetWidth = 453, offsetHeight = 475}, -- 108: Pico Idle Dance0007
		{x = 4130, y = 3530, width = 443, height = 475, offsetX = 0, offsetY = 0, offsetWidth = 453, offsetHeight = 475}, -- 109: Pico Idle Dance0008
		{x = 4130, y = 3530, width = 443, height = 475, offsetX = 0, offsetY = 0, offsetWidth = 453, offsetHeight = 475}, -- 110: Pico Idle Dance0009
		{x = 4130, y = 3530, width = 443, height = 475, offsetX = 0, offsetY = 0, offsetWidth = 453, offsetHeight = 475}, -- 111: Pico Idle Dance0010
		{x = 4130, y = 3530, width = 443, height = 475, offsetX = 0, offsetY = 0, offsetWidth = 453, offsetHeight = 475}, -- 112: Pico Idle Dance0011
		{x = 4130, y = 3530, width = 443, height = 475, offsetX = 0, offsetY = 0, offsetWidth = 453, offsetHeight = 475}, -- 113: Pico Idle Dance0012
		{x = 4130, y = 3530, width = 443, height = 475, offsetX = 0, offsetY = 0, offsetWidth = 453, offsetHeight = 475}, -- 114: Pico Idle Dance0013
		{x = 4586, y = 5457, width = 449, height = 462, offsetX = -6, offsetY = -2, offsetWidth = 455, offsetHeight = 464}, -- 115: Pico NOTE LEFT0000
		{x = 4586, y = 5457, width = 449, height = 462, offsetX = -6, offsetY = -2, offsetWidth = 455, offsetHeight = 464}, -- 116: Pico NOTE LEFT0001
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 117: Pico NOTE LEFT0002
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 118: Pico NOTE LEFT0003
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 119: Pico NOTE LEFT0004
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 120: Pico NOTE LEFT0005
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 121: Pico NOTE LEFT0006
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 122: Pico NOTE LEFT0007
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 123: Pico NOTE LEFT0008
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 124: Pico NOTE LEFT0009
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 125: Pico NOTE LEFT0010
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 126: Pico NOTE LEFT0011
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 127: Pico NOTE LEFT0012
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 128: Pico NOTE LEFT0013
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 129: Pico NOTE LEFT0014
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 130: Pico NOTE LEFT0015
		{x = 4129, y = 5457, width = 455, height = 464, offsetX = 0, offsetY = 0, offsetWidth = 0, offsetHeight = 0}, -- 131: Pico NOTE LEFT0016
		{x = 5037, y = 5457, width = 449, height = 462, offsetX = -6, offsetY = -37, offsetWidth = 461, offsetHeight = 500}, -- 132: Pico NOTE LEFT miss0000
		{x = 1081, y = 3010, width = 459, height = 500, offsetX = -2, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 133: Pico NOTE LEFT miss0001
		{x = 1081, y = 3010, width = 459, height = 500, offsetX = -2, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 134: Pico NOTE LEFT miss0002
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 135: Pico NOTE LEFT miss0003
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 136: Pico NOTE LEFT miss0004
		{x = 2004, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 137: Pico NOTE LEFT miss0005
		{x = 2004, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 138: Pico NOTE LEFT miss0006
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 139: Pico NOTE LEFT miss0007
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 140: Pico NOTE LEFT miss0008
		{x = 2004, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 141: Pico NOTE LEFT miss0009
		{x = 2004, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 142: Pico NOTE LEFT miss0010
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 143: Pico NOTE LEFT miss0011
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 144: Pico NOTE LEFT miss0012
		{x = 2004, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 145: Pico NOTE LEFT miss0013
		{x = 2004, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 146: Pico NOTE LEFT miss0014
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 147: Pico NOTE LEFT miss0015
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 148: Pico NOTE LEFT miss0016
		{x = 2004, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 149: Pico NOTE LEFT miss0017
		{x = 2004, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 150: Pico NOTE LEFT miss0018
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 151: Pico NOTE LEFT miss0019
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 152: Pico NOTE LEFT miss0020
		{x = 2004, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 153: Pico NOTE LEFT miss0021
		{x = 2004, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 154: Pico NOTE LEFT miss0022
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 155: Pico NOTE LEFT miss0023
		{x = 1542, y = 3010, width = 460, height = 500, offsetX = 0, offsetY = 0, offsetWidth = 461, offsetHeight = 500}, -- 156: Pico NOTE LEFT miss0024
		{x = 2324, y = 3530, width = 458, height = 476, offsetX = -1, offsetY = 0, offsetWidth = 459, offsetHeight = 476}, -- 157: Pico Note Right0000
		{x = 2324, y = 3530, width = 458, height = 476, offsetX = -1, offsetY = 0, offsetWidth = 459, offsetHeight = 476}, -- 158: Pico Note Right0001
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 159: Pico Note Right0002
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 160: Pico Note Right0003
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 161: Pico Note Right0004
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 162: Pico Note Right0005
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 163: Pico Note Right0006
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 164: Pico Note Right0007
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 165: Pico Note Right0008
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 166: Pico Note Right0009
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 167: Pico Note Right0010
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 168: Pico Note Right0011
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 169: Pico Note Right0012
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 170: Pico Note Right0013
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 171: Pico Note Right0014
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 172: Pico Note Right0015
		{x = 444, y = 4981, width = 442, height = 473, offsetX = 0, offsetY = -3, offsetWidth = 459, offsetHeight = 476}, -- 173: Pico Note Right0016
		{x = 2784, y = 3530, width = 458, height = 476, offsetX = -11, offsetY = -46, offsetWidth = 469, offsetHeight = 522}, -- 174: Pico Note Right Miss0000
		{x = 4433, y = 2461, width = 443, height = 522, offsetX = 0, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 175: Pico Note Right Miss0001
		{x = 4433, y = 2461, width = 443, height = 522, offsetX = 0, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 176: Pico Note Right Miss0002
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 177: Pico Note Right Miss0003
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 178: Pico Note Right Miss0004
		{x = 5325, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 179: Pico Note Right Miss0005
		{x = 5325, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 180: Pico Note Right Miss0006
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 181: Pico Note Right Miss0007
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 182: Pico Note Right Miss0008
		{x = 5325, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 183: Pico Note Right Miss0009
		{x = 5325, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 184: Pico Note Right Miss0010
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 185: Pico Note Right Miss0011
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 186: Pico Note Right Miss0012
		{x = 5325, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 187: Pico Note Right Miss0013
		{x = 5325, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 188: Pico Note Right Miss0014
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 189: Pico Note Right Miss0015
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 190: Pico Note Right Miss0016
		{x = 5325, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 191: Pico Note Right Miss0017
		{x = 5325, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 192: Pico Note Right Miss0018
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 193: Pico Note Right Miss0019
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 194: Pico Note Right Miss0020
		{x = 5325, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 195: Pico Note Right Miss0021
		{x = 5325, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 196: Pico Note Right Miss0022
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 197: Pico Note Right Miss0023
		{x = 4878, y = 2461, width = 445, height = 522, offsetX = -1, offsetY = 0, offsetWidth = 469, offsetHeight = 522}, -- 198: Pico Note Right Miss0024
		{x = 6299, y = 3010, width = 432, height = 495, offsetX = 0, offsetY = 0, offsetWidth = 433, offsetHeight = 495}, -- 199: pico Up note0000
		{x = 6299, y = 3010, width = 432, height = 495, offsetX = 0, offsetY = 0, offsetWidth = 433, offsetHeight = 495}, -- 200: pico Up note0001
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 201: pico Up note0002
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 202: pico Up note0003
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 203: pico Up note0004
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 204: pico Up note0005
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 205: pico Up note0006
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 206: pico Up note0007
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 207: pico Up note0008
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 208: pico Up note0009
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 209: pico Up note0010
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 210: pico Up note0011
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 211: pico Up note0012
		{x = 1458, y = 3530, width = 432, height = 490, offsetX = -1, offsetY = -5, offsetWidth = 433, offsetHeight = 495}, -- 212: pico Up note0013
		{x = 0, y = 3530, width = 432, height = 495, offsetX = -8, offsetY = -36, offsetWidth = 451, offsetHeight = 531}, -- 213: pico Up note miss0000
		{x = 3980, y = 2461, width = 451, height = 526, offsetX = 0, offsetY = -4, offsetWidth = 451, offsetHeight = 531}, -- 214: pico Up note miss0001
		{x = 3980, y = 2461, width = 451, height = 526, offsetX = 0, offsetY = -4, offsetWidth = 451, offsetHeight = 531}, -- 215: pico Up note miss0002
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 216: pico Up note miss0003
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 217: pico Up note miss0004
		{x = 3534, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 218: pico Up note miss0005
		{x = 3534, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 219: pico Up note miss0006
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 220: pico Up note miss0007
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 221: pico Up note miss0008
		{x = 3534, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 222: pico Up note miss0009
		{x = 3534, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 223: pico Up note miss0010
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 224: pico Up note miss0011
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 225: pico Up note miss0012
		{x = 3534, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 226: pico Up note miss0013
		{x = 3534, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 227: pico Up note miss0014
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 228: pico Up note miss0015
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 229: pico Up note miss0016
		{x = 3534, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 230: pico Up note miss0017
		{x = 3534, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 231: pico Up note miss0018
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 232: pico Up note miss0019
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 233: pico Up note miss0020
		{x = 3534, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 234: pico Up note miss0021
		{x = 3534, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 235: pico Up note miss0022
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 236: pico Up note miss0023
		{x = 3088, y = 2461, width = 444, height = 530, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 531}, -- 237: pico Up note miss0024
		{x = 5925, y = 5457, width = 435, height = 461, offsetX = -75, offsetY = -13, offsetWidth = 510, offsetHeight = 475}, -- 238: Pico Gets Pissed0000
		{x = 5925, y = 5457, width = 435, height = 461, offsetX = -75, offsetY = -13, offsetWidth = 510, offsetHeight = 475}, -- 239: Pico Gets Pissed0001
		{x = 983, y = 5457, width = 442, height = 468, offsetX = -68, offsetY = -6, offsetWidth = 510, offsetHeight = 475}, -- 240: Pico Gets Pissed0002
		{x = 983, y = 5457, width = 442, height = 468, offsetX = -68, offsetY = -6, offsetWidth = 510, offsetHeight = 475}, -- 241: Pico Gets Pissed0003
		{x = 3536, y = 4981, width = 448, height = 469, offsetX = -58, offsetY = -6, offsetWidth = 510, offsetHeight = 475}, -- 242: Pico Gets Pissed0004
		{x = 3986, y = 4981, width = 444, height = 469, offsetX = -58, offsetY = -6, offsetWidth = 510, offsetHeight = 475}, -- 243: Pico Gets Pissed0005
		{x = 6240, y = 4504, width = 444, height = 474, offsetX = -58, offsetY = -1, offsetWidth = 510, offsetHeight = 475}, -- 244: Pico Gets Pissed0006
		{x = 0, y = 4981, width = 442, height = 474, offsetX = -58, offsetY = -1, offsetWidth = 510, offsetHeight = 475}, -- 245: Pico Gets Pissed0007
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 246: Pico Gets Pissed0008
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 247: Pico Gets Pissed0009
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 248: Pico Gets Pissed0010
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 249: Pico Gets Pissed0011
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 250: Pico Gets Pissed0012
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 251: Pico Gets Pissed0013
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 252: Pico Gets Pissed0014
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 253: Pico Gets Pissed0015
		{x = 5020, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 254: Pico Gets Pissed0016
		{x = 5020, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 255: Pico Gets Pissed0017
		{x = 5020, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 256: Pico Gets Pissed0018
		{x = 5020, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 257: Pico Gets Pissed0019
		{x = 5465, y = 3530, width = 443, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 258: Pico Gets Pissed0020
		{x = 5910, y = 3530, width = 435, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 259: Pico Gets Pissed0021
		{x = 6347, y = 3530, width = 430, height = 475, offsetX = -62, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 260: Pico Gets Pissed0022
		{x = 0, y = 4027, width = 423, height = 475, offsetX = -62, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 261: Pico Gets Pissed0023
		{x = 425, y = 4027, width = 428, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 262: Pico Gets Pissed0024
		{x = 855, y = 4027, width = 406, height = 475, offsetX = -57, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 263: Pico Gets Pissed0025
		{x = 1263, y = 4027, width = 425, height = 475, offsetX = -38, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 264: Pico Gets Pissed0026
		{x = 1690, y = 4027, width = 463, height = 475, offsetX = 0, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 265: Pico Gets Pissed0027
		{x = 2155, y = 4027, width = 463, height = 475, offsetX = 0, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 266: Pico Gets Pissed0028
		{x = 2620, y = 4027, width = 453, height = 475, offsetX = -10, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 267: Pico Gets Pissed0029
		{x = 3075, y = 4027, width = 453, height = 475, offsetX = -10, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 268: Pico Gets Pissed0030
		{x = 3530, y = 4027, width = 447, height = 475, offsetX = -16, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 269: Pico Gets Pissed0031
		{x = 3979, y = 4027, width = 447, height = 475, offsetX = -16, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 270: Pico Gets Pissed0032
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 271: Pico Gets Pissed0033
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 272: Pico Gets Pissed0034
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 273: Pico Gets Pissed0035
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 274: Pico Gets Pissed0036
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 275: Pico Gets Pissed0037
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 276: Pico Gets Pissed0038
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 277: Pico Gets Pissed0039
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 278: Pico Gets Pissed0040
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 279: Pico Gets Pissed0041
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 280: Pico Gets Pissed0042
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 281: Pico Gets Pissed0043
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 282: Pico Gets Pissed0044
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 283: Pico Gets Pissed0045
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 284: Pico Gets Pissed0046
		{x = 4876, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 285: Pico Gets Pissed0047
		{x = 4876, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 286: Pico Gets Pissed0048
		{x = 4876, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 287: Pico Gets Pissed0049
		{x = 5324, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 288: Pico Gets Pissed0050
		{x = 5324, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 289: Pico Gets Pissed0051
		{x = 5772, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 290: Pico Gets Pissed0052
		{x = 6220, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 291: Pico Gets Pissed0053
		{x = 6220, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 292: Pico Gets Pissed0054
		{x = 6220, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 293: Pico Gets Pissed0055
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 294: Pico Gets Pissed0056
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 295: Pico Gets Pissed0057
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 296: Pico Gets Pissed0058
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 297: Pico Gets Pissed0059
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 298: Pico Gets Pissed0060
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 299: Pico Gets Pissed0061
		{x = 4428, y = 4027, width = 446, height = 475, offsetX = -17, offsetY = 0, offsetWidth = 510, offsetHeight = 475}, -- 300: Pico Gets Pissed0062
		{x = 2784, y = 5457, width = 451, height = 467, offsetX = -6, offsetY = -1, offsetWidth = 457, offsetHeight = 476}, -- 301: cutscene cock0000
		{x = 3237, y = 5457, width = 451, height = 467, offsetX = -6, offsetY = -1, offsetWidth = 457, offsetHeight = 476}, -- 302: cutscene cock0001
		{x = 1764, y = 4981, width = 436, height = 470, offsetX = -10, offsetY = 0, offsetWidth = 457, offsetHeight = 476}, -- 303: cutscene cock0002
		{x = 2202, y = 4981, width = 436, height = 470, offsetX = -10, offsetY = 0, offsetWidth = 457, offsetHeight = 476}, -- 304: cutscene cock0003
		{x = 2202, y = 4981, width = 436, height = 470, offsetX = -10, offsetY = 0, offsetWidth = 457, offsetHeight = 476}, -- 305: cutscene cock0004
		{x = 3690, y = 5457, width = 437, height = 466, offsetX = -4, offsetY = -5, offsetWidth = 457, offsetHeight = 476}, -- 306: cutscene cock0005
		{x = 3690, y = 5457, width = 437, height = 466, offsetX = -4, offsetY = -5, offsetWidth = 457, offsetHeight = 476}, -- 307: cutscene cock0006
		{x = 1427, y = 5457, width = 449, height = 468, offsetX = 0, offsetY = -8, offsetWidth = 457, offsetHeight = 476}, -- 308: cutscene cock0007
		{x = 1427, y = 5457, width = 449, height = 468, offsetX = 0, offsetY = -8, offsetWidth = 457, offsetHeight = 476}, -- 309: cutscene cock0008
		{x = 2476, y = 698, width = 642, height = 600, offsetX = -124, offsetY = -95, offsetWidth = 766, offsetHeight = 706}, -- 310: shoot and return0000
		{x = 768, y = 0, width = 766, height = 695, offsetX = 0, offsetY = 0, offsetWidth = 766, offsetHeight = 706}, -- 311: shoot and return0001
		{x = 3375, y = 5928, width = 482, height = 433, offsetX = -281, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 312: shoot and return0002
		{x = 3859, y = 5928, width = 477, height = 433, offsetX = -286, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 313: shoot and return0003
		{x = 4338, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 314: shoot and return0004
		{x = 4338, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 315: shoot and return0005
		{x = 4338, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 316: shoot and return0006
		{x = 4338, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 317: shoot and return0007
		{x = 4338, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 318: shoot and return0008
		{x = 4338, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 319: shoot and return0009
		{x = 4338, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 320: shoot and return0010
		{x = 4338, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 321: shoot and return0011
		{x = 4338, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 322: shoot and return0012
		{x = 4338, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 323: shoot and return0013
		{x = 4813, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 324: shoot and return0014
		{x = 4813, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 325: shoot and return0015
		{x = 4813, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 326: shoot and return0016
		{x = 4813, y = 5928, width = 473, height = 433, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 706}, -- 327: shoot and return0017
		{x = 5785, y = 5928, width = 469, height = 432, offsetX = -294, offsetY = -263, offsetWidth = 766, offsetHeight = 706}, -- 328: shoot and return0018
		{x = 5785, y = 5928, width = 469, height = 432, offsetX = -294, offsetY = -263, offsetWidth = 766, offsetHeight = 706}, -- 329: shoot and return0019
		{x = 5785, y = 5928, width = 469, height = 432, offsetX = -294, offsetY = -263, offsetWidth = 766, offsetHeight = 706}, -- 330: shoot and return0020
		{x = 5785, y = 5928, width = 469, height = 432, offsetX = -294, offsetY = -263, offsetWidth = 766, offsetHeight = 706}, -- 331: shoot and return0021
		{x = 6256, y = 5928, width = 460, height = 431, offsetX = -297, offsetY = -264, offsetWidth = 766, offsetHeight = 706}, -- 332: shoot and return0022
		{x = 6256, y = 5928, width = 460, height = 431, offsetX = -297, offsetY = -264, offsetWidth = 766, offsetHeight = 706}, -- 333: shoot and return0023
		{x = 6256, y = 5928, width = 460, height = 431, offsetX = -297, offsetY = -264, offsetWidth = 766, offsetHeight = 706}, -- 334: shoot and return0024
		{x = 1498, y = 5928, width = 437, height = 436, offsetX = -301, offsetY = -261, offsetWidth = 766, offsetHeight = 706}, -- 335: shoot and return0025
		{x = 1498, y = 5928, width = 437, height = 436, offsetX = -301, offsetY = -261, offsetWidth = 766, offsetHeight = 706}, -- 336: shoot and return0026
		{x = 1090, y = 5928, width = 406, height = 444, offsetX = -293, offsetY = -256, offsetWidth = 766, offsetHeight = 706}, -- 337: shoot and return0027
		{x = 1090, y = 5928, width = 406, height = 444, offsetX = -293, offsetY = -256, offsetWidth = 766, offsetHeight = 706}, -- 338: shoot and return0028
		{x = 1892, y = 3530, width = 430, height = 477, offsetX = -252, offsetY = -229, offsetWidth = 766, offsetHeight = 706}, -- 339: shoot and return0029
		{x = 1892, y = 3530, width = 430, height = 477, offsetX = -252, offsetY = -229, offsetWidth = 766, offsetHeight = 706}, -- 340: shoot and return0030
		{x = 3244, y = 3530, width = 439, height = 476, offsetX = -252, offsetY = -230, offsetWidth = 766, offsetHeight = 706}, -- 341: shoot and return0031
		{x = 3244, y = 3530, width = 439, height = 476, offsetX = -252, offsetY = -230, offsetWidth = 766, offsetHeight = 706}, -- 342: shoot and return0032
		{x = 0, y = 4504, width = 442, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 343: shoot and return0033
		{x = 0, y = 4504, width = 442, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 344: shoot and return0034
		{x = 0, y = 4504, width = 442, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 345: shoot and return0035
		{x = 3685, y = 3530, width = 443, height = 476, offsetX = -252, offsetY = -230, offsetWidth = 766, offsetHeight = 706}, -- 346: shoot and return0036
		{x = 3685, y = 3530, width = 443, height = 476, offsetX = -252, offsetY = -230, offsetWidth = 766, offsetHeight = 706}, -- 347: shoot and return0037
		{x = 3685, y = 3530, width = 443, height = 476, offsetX = -252, offsetY = -230, offsetWidth = 766, offsetHeight = 706}, -- 348: shoot and return0038
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 349: shoot and return0039
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 350: shoot and return0040
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 351: shoot and return0041
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 352: shoot and return0042
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 353: shoot and return0043
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 354: shoot and return0044
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 355: shoot and return0045
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 356: shoot and return0046
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 357: shoot and return0047
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 358: shoot and return0048
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 359: shoot and return0049
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 360: shoot and return0050
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 361: shoot and return0051
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 362: shoot and return0052
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 363: shoot and return0053
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 364: shoot and return0054
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 365: shoot and return0055
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 366: shoot and return0056
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 367: shoot and return0057
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 368: shoot and return0058
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 369: shoot and return0059
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 370: shoot and return0060
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 371: shoot and return0061
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 372: shoot and return0062
		{x = 890, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 373: shoot and return0063
		{x = 890, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 374: shoot and return0064
		{x = 890, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 375: shoot and return0065
		{x = 1336, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 376: shoot and return0066
		{x = 1336, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 377: shoot and return0067
		{x = 1782, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 378: shoot and return0068
		{x = 1782, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 379: shoot and return0069
		{x = 2228, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 380: shoot and return0070
		{x = 2228, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 381: shoot and return0071
		{x = 2228, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 382: shoot and return0072
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 383: shoot and return0073
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 384: shoot and return0074
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 385: shoot and return0075
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 386: shoot and return0076
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 387: shoot and return0077
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 388: shoot and return0078
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 389: shoot and return0079
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 390: shoot and return0080
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 391: shoot and return0081
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 392: shoot and return0082
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 393: shoot and return0083
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 394: shoot and return0084
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 395: shoot and return0085
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 396: shoot and return0086
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 397: shoot and return0087
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 398: shoot and return0088
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 399: shoot and return0089
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 400: shoot and return0090
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 401: shoot and return0091
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 402: shoot and return0092
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 403: shoot and return0093
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 404: shoot and return0094
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 405: shoot and return0095
		{x = 444, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 406: shoot and return0096
		{x = 890, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 407: shoot and return0097
		{x = 890, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 408: shoot and return0098
		{x = 890, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 409: shoot and return0099
		{x = 2674, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 410: shoot and return0100
		{x = 2674, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 411: shoot and return0101
		{x = 3120, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 412: shoot and return0102
		{x = 3120, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 413: shoot and return0103
		{x = 3566, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 414: shoot and return0104
		{x = 3566, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 415: shoot and return0105
		{x = 4012, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 416: shoot and return0106
		{x = 4012, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 417: shoot and return0107
		{x = 4012, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 418: shoot and return0108
		{x = 4458, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 419: shoot and return0109
		{x = 4458, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 420: shoot and return0110
		{x = 4458, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 421: shoot and return0111
		{x = 4904, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 422: shoot and return0112
		{x = 4904, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 423: shoot and return0113
		{x = 4904, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 424: shoot and return0114
		{x = 4904, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 425: shoot and return0115
		{x = 4904, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 426: shoot and return0116
		{x = 4904, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 427: shoot and return0117
		{x = 4904, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 428: shoot and return0118
		{x = 4904, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 429: shoot and return0119
		{x = 4904, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 430: shoot and return0120
		{x = 4904, y = 4504, width = 444, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 766, offsetHeight = 706}, -- 431: shoot and return0121
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 510, offsetHeight = 475}, -- 432: shoot and return0122
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 510, offsetHeight = 475}, -- 433: shoot and return0123
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 510, offsetHeight = 475}, -- 434: shoot and return0124
		{x = 5925, y = 5457, width = 435, height = 461, offsetX = -271, offsetY = -244, offsetWidth = 510, offsetHeight = 475}, -- 435: shoot and return0125
		{x = 5925, y = 5457, width = 435, height = 461, offsetX = -271, offsetY = -244, offsetWidth = 510, offsetHeight = 475}, -- 436: shoot and return0126
		{x = 983, y = 5457, width = 442, height = 468, offsetX = -264, offsetY = -237, offsetWidth = 510, offsetHeight = 475}, -- 437: shoot and return0127
		{x = 983, y = 5457, width = 442, height = 468, offsetX = -264, offsetY = -237, offsetWidth = 510, offsetHeight = 475}, -- 438: shoot and return0128
		{x = 3536, y = 4981, width = 448, height = 469, offsetX = -254, offsetY = -238, offsetWidth = 510, offsetHeight = 475}, -- 439: shoot and return0129
		{x = 3986, y = 4981, width = 444, height = 469, offsetX = -254, offsetY = -238, offsetWidth = 510, offsetHeight = 475}, -- 440: shoot and return0130
		{x = 6240, y = 4504, width = 444, height = 474, offsetX = -253, offsetY = -232, offsetWidth = 510, offsetHeight = 475}, -- 441: shoot and return0131
		{x = 0, y = 4981, width = 442, height = 474, offsetX = -253, offsetY = -232, offsetWidth = 510, offsetHeight = 475}, -- 442: shoot and return0132
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 510, offsetHeight = 475}, -- 443: shoot and return0133
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 510, offsetHeight = 475}, -- 444: shoot and return0134
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 510, offsetHeight = 475}, -- 445: shoot and return0135
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 510, offsetHeight = 475}, -- 446: shoot and return0136
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 510, offsetHeight = 475}, -- 447: shoot and return0137
		{x = 4575, y = 3530, width = 443, height = 475, offsetX = -252, offsetY = -231, offsetWidth = 510, offsetHeight = 475}, -- 448: shoot and return0138
		{x = 0, y = 5928, width = 543, height = 453, offsetX = -5, offsetY = -15, offsetWidth = 548, offsetHeight = 469}, -- 449: Pico Hit Can0001.png
		{x = 545, y = 5928, width = 543, height = 452, offsetX = -5, offsetY = -16, offsetWidth = 548, offsetHeight = 469}, -- 450: Pico Hit Can0002.png
		{x = 4432, y = 4981, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 451: Pico Hit Can0003.png
		{x = 4971, y = 4981, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 452: Pico Hit Can0004.png
		{x = 5510, y = 4981, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 453: Pico Hit Can0005.png
		{x = 6049, y = 4981, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 454: Pico Hit Can0006.png
		{x = 0, y = 5457, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 455: Pico Hit Can0007.png
		{x = 5510, y = 4981, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 456: Pico Hit Can0008.png
		{x = 6049, y = 4981, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 457: Pico Hit Can0009.png
		{x = 0, y = 5457, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 458: Pico Hit Can0010.png
		{x = 5510, y = 4981, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 459: Pico Hit Can0011.png
		{x = 6049, y = 4981, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 460: Pico Hit Can0012.png
		{x = 0, y = 5457, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 461: Pico Hit Can0013.png
		{x = 5510, y = 4981, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 462: Pico Hit Can0014.png
		{x = 6049, y = 4981, width = 537, height = 469, offsetX = 0, offsetY = 0, offsetWidth = 548, offsetHeight = 469}, -- 463: Pico Hit Can0015.png
		{x = 1878, y = 5457, width = 451, height = 468, offsetX = 0, offsetY = -1, offsetWidth = 451, offsetHeight = 471}, -- 464: Pico Reload0001.png
		{x = 2331, y = 5457, width = 451, height = 468, offsetX = 0, offsetY = -1, offsetWidth = 451, offsetHeight = 471}, -- 465: Pico Reload0002.png
		{x = 888, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 466: Pico Reload0003.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 467: Pico Reload0004.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 468: Pico Reload0005.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 469: Pico Reload0006.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 470: Pico Reload0007.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 471: Pico Reload0008.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 472: Pico Reload0009.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 473: Pico Reload0010.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 474: Pico Reload0011.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 475: Pico Reload0012.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 476: Pico Reload0013.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 477: Pico Reload0014.png
		{x = 1326, y = 4981, width = 436, height = 471, offsetX = -4, offsetY = 0, offsetWidth = 451, offsetHeight = 471}, -- 478: Pico Reload0015.png
		{x = 1832, y = 698, width = 642, height = 602, offsetX = -124, offsetY = -94, offsetWidth = 766, offsetHeight = 696}, -- 479: Pico Shoot Hip Full0001.png
		{x = 0, y = 0, width = 766, height = 696, offsetX = 0, offsetY = 0, offsetWidth = 766, offsetHeight = 696}, -- 480: Pico Shoot Hip Full0002.png
		{x = 1937, y = 5928, width = 482, height = 434, offsetX = -281, offsetY = -262, offsetWidth = 766, offsetHeight = 696}, -- 481: Pico Shoot Hip Full0003.png
		{x = 2421, y = 5928, width = 477, height = 434, offsetX = -286, offsetY = -262, offsetWidth = 766, offsetHeight = 696}, -- 482: Pico Shoot Hip Full0004.png
		{x = 2900, y = 5928, width = 473, height = 434, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 696}, -- 483: Pico Shoot Hip Full0005.png
		{x = 2900, y = 5928, width = 473, height = 434, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 696}, -- 484: Pico Shoot Hip Full0006.png
		{x = 2900, y = 5928, width = 473, height = 434, offsetX = -290, offsetY = -262, offsetWidth = 766, offsetHeight = 696}, -- 485: Pico Shoot Hip Full0007.png
	},
	{
		["Pico Gets Pissed"] = {start = 238, stop = 300, speed = 24, offsetX = 25, offsetY = 0},
		["Pico Hit Can"] = {start = 449, stop = 463, speed = 24, offsetX = -70, offsetY = -5},
		["down alt"] = {start = 464, stop = 478, speed = 24, offsetX = 70, offsetY = 0},
		["left alt"] = {start = 479, stop = 485, speed = 24, offsetX = 190, offsetY = 125},
		["cutscene cock"] = {start = 301, stop = 309, speed = 24, offsetX = 0, offsetY = 0},
		["dead"] = {start = 1, stop = 64, speed = 24, offsetX = -100, offsetY = 20},
		["down"] = {start = 65, stop = 75, speed = 24, offsetX = -40, offsetY = -45},
		["idle"] = {start = 101, stop = 114, speed = 24, offsetX = 0, offsetY = 0},
		["left"] = {start = 115, stop = 131, speed = 24, offsetX = 80, offsetY = -5},
		["miss down"] = {start = 76, stop = 100, speed = 24, offsetX = -50, offsetY = -5},
		["miss left"] = {start = 132, stop = 156, speed = 24, offsetX = 74, offsetY = 15},
		["miss right"] = {start = 174, stop = 198, speed = 24, offsetX = -55, offsetY = 25},
		["miss up"] = {start = 213, stop = 237, speed = 24, offsetX = 20, offsetY = 40},
		["right"] = {start = 157, stop = 173, speed = 24, offsetX = -60, offsetY = 0},
		["shoot and return"] = {start = 310, stop = 448, speed = 24, offsetX = 85, offsetY = 110},
		["up"] = {start = 199, stop = 212, speed = 24, offsetX = 25, offsetY = 10}
	},
	"idle"
)

return Pico_FNF_assetss