return {
    layers = {
        {
            path = "png/weekend1/phillyBlazin/skyBlur",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = -96,
            y = -274,
        },
        {
            path = "weekend1/lightning",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = 131.66666666667,
            y = -361.66666666667,
        },
        {
            path = "weekend1/lightning",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -457.5,
            y = -360.25,
        },
        {
            path = "png/weekend1/phillyBlazin/streetBlur",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = 0,
            y = 0,
        },
        {
            path = "weekend1/AbotSystem",
            scaleX = 0.8,
            scaleY = 0.8,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -91.746031746032,
            y = 99.841269841266,
        },
        {
            path = "weekend1/Nene",
            scaleX = 0.8,
            scaleY = 0.8,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -128.73015873015,
            y = -96.666666666667,
        },
        {
            path = "weekend1/Darnell Fighting Animations V2",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -224.58333333333,
            y = -55,
        },
        {
            path = "weekend1/Pico Fighting Animations V2",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = 158.05555555555,
            y = -39.166666666667,
        },
    },
    marks = {
        {
            color = {
                0,
                1,
                0,
            },
            name = "BF",
            x = 0,
            y = 0,
        },
        {
            color = {
                1,
                0,
                1,
            },
            name = "GF",
            x = 0,
            y = 0,
        },
        {
            color = {
                1,
                0,
                0,
            },
            name = "Enemy",
            x = 0,
            y = 0,
        },
    },
}