return {
    layers = {
        {
            path = "png/FunInfiniteStage/sonicFUNsky",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = -3.3333333333333,
            y = -85,
        },
        {
            path = "png/FunInfiniteStage/Bush2",
            scaleX = 1.3,
            scaleY = 1.3,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = 3.3333333333333,
            y = 143.33333333333,
        },
        {
            path = "FunInfiniteStage/MajinBoppersBack",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -246.27777777778,
            y = -334.5,
        },
        {
            path = "png/FunInfiniteStage/Bush 1",
            scaleX = 1.2,
            scaleY = 1.2,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = 3.3333333333333,
            y = 120,
        },
        {
            path = "FunInfiniteStage/MajinBoppersFront",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -131.33333333333,
            y = -255.33333333333,
        },
        {
            path = "png/FunInfiniteStage/floor BG",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = 8.3333333333333,
            y = 410,
        },
        {
            path = "girlfriend",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = false,
            x = 0,
            y = 0,
        },
        {
            path = "MajinOG",
            scaleX = 1.5,
            scaleY = 1.5,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -443,
            y = 110.5,
        },
        {
            path = "endless_bf",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = 227.5,
            y = 225,
        },
        {
            path = "FunInfiniteStage/majinFG1",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = 687.5,
            y = 555,
        },
        {
            path = "FunInfiniteStage/majinFG2",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -1023.3333333333,
            y = 570,
        },
    },
    marks = {
        {
            color = {
                0,
                1,
                0,
            },
            name = "BF",
            x = 0,
            y = 0,
        },
        {
            color = {
                1,
                0,
                1,
            },
            name = "GF",
            x = 0,
            y = 0,
        },
        {
            color = {
                1,
                0,
                0,
            },
            name = "Enemy",
            x = 0,
            y = 0,
        },
    },
}