return {
    marks = {
        [1] = {
            color = {
                [1] = 0,
                [2] = 1,
                [3] = 0,
            },
            name = "BF",
            x = 0,
            y = 0,
        },
        [2] = {
            color = {
                [1] = 1,
                [2] = 0,
                [3] = 1,
            },
            name = "GF",
            x = 0,
            y = 0,
        },
        [3] = {
            color = {
                [1] = 1,
                [2] = 0,
                [3] = 0,
            },
            name = "Enemy",
            x = 0,
            y = 0,
        },
    },
    layers = {
        [1] = {
            x = 0,
            y = 0,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/bg",
            type = "image",
        },
        [2] = {
            x = -15,
            y = 1025,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/floor",
            type = "image",
        },
        [3] = {
            x = -75,
            y = 525,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/back-tables",
            type = "image",
        },
        [4] = {
            x = -160,
            y = 675,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/back-stools",
            type = "image",
        },
        [5] = {
            x = 45,
            y = 295,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/truck-stuff",
            type = "image",
        },
        [6] = {
            x = -1575,
            y = 315,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/truck-door",
            type = "image",
        },
        [7] = {
            x = 475,
            y = 1160,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/front-stool",
            type = "image",
        },
        [8] = {
            x = -295,
            y = 210,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/lights/truck-light1",
            type = "image",
        },
        [9] = {
            x = -277,
            y = 219,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/lights/truck-light2",
            type = "image",
        },
        [10] = {
            x = 796.66666666667,
            y = 858.33333333333,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/sakura",
            type = "sprite",
        },
        [11] = {
            x = 291.83333333333,
            y = 362.33333333333,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 0.7,
            scaleY = 0.7,
            path = "sserafim/gf_truck",
            type = "sprite",
        },
        [12] = {
            x = -1330.3333333333,
            y = 343.16666666667,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 0.7,
            scaleY = 0.7,
            path = "sserafim/yunjin",
            type = "sprite",
        },
        [13] = {
            x = -620,
            y = 723.33333333333,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/kazuha",
            type = "sprite",
        },
        [14] = {
            x = 167.5,
            y = 825,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/eunchae",
            type = "sprite",
        },
        [15] = {
            x = 60.833333333333,
            y = 320.83333333333,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "sserafim/chaewon",
            type = "sprite",
        },
        [16] = {
            x = 646.41025641025,
            y = 982.17948717945,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "nastyObject",
            type = "image",
        },
        [17] = {
            x = -516.5,
            y = 311.5,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "nastyObject2",
            type = "image",
        },
        [18] = {
            x = 254,
            y = 528,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "nastyObject3",
            type = "image",
        },
        [19] = {
            x = 112,
            y = 306,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "nastyObject4",
            type = "image",
        },
        [20] = {
            x = -212.5,
            y = 570,
            visible = true,
            scrollX = 1,
            scrollY = 1,
            scaleX = 1,
            scaleY = 1,
            path = "nastyObject5",
            type = "image",
        },
    },
}