return {
    marks = {
        [1] = {
            name = "BF",
            x = 0,
            y = 0,
            color = {
                [1] = 0,
                [2] = 1,
                [3] = 0,
            },
        },
        [2] = {
            name = "GF",
            x = 0,
            y = 0,
            color = {
                [1] = 1,
                [2] = 0,
                [3] = 1,
            },
        },
        [3] = {
            name = "Enemy",
            x = 0,
            y = 0,
            color = {
                [1] = 1,
                [2] = 0,
                [3] = 0,
            },
        },
    },
    layers = {
        [1] = {
            visible = true,
            scrollX = 1,
            scaleX = 1,
            scaleY = 1,
            path = "P2/sky",
            type = "image",
            y = 0,
            x = 0,
            scrollY = 1,
        },
        [2] = {
            visible = true,
            scrollX = 1,
            scaleX = 1,
            scaleY = 1,
            path = "P2/GrassBack",
            type = "image",
            y = 0,
            x = 0,
            scrollY = 1,
        },
        [3] = {
            visible = true,
            scrollX = 1,
            scaleX = 1,
            scaleY = 1,
            path = "P2/trees",
            type = "image",
            y = 0,
            x = 0,
            scrollY = 1,
        },
        [4] = {
            visible = true,
            scrollX = 1,
            scaleX = 1,
            scaleY = 1,
            path = "P2/Grass",
            type = "image",
            y = 0,
            x = 0,
            scrollY = 1,
        },
        [5] = {
            visible = true,
            scrollX = 1,
            scaleX = 1,
            scaleY = 1,
            path = "girlfriend",
            type = "sprite",
            y = -141.66666666667,
            x = 9.1666666666667,
            scrollY = 1,
        },
        [6] = {
            visible = true,
            scrollX = 1,
            scaleX = 1,
            scaleY = 1,
            path = "YCR",
            type = "sprite",
            y = -85,
            x = -391.66666666666,
            scrollY = 1,
        },
        [7] = {
            visible = true,
            scrollX = 1,
            scaleX = 1,
            scaleY = 1,
            path = "boyfriend",
            type = "sprite",
            y = 56.666666666667,
            x = 384.16666666667,
            scrollY = 1,
        },
        [8] = {
            visible = true,
            scrollX = 1,
            scaleX = 1,
            scaleY = 1,
            path = "P2/TreesFront",
            type = "image",
            y = 0,
            x = 0,
            scrollY = 1,
        },
        [9] = {
            visible = true,
            scrollX = 1,
            scaleX = 8.5,
            scaleY = 8.5,
            path = "P2/GreenHill",
            type = "image",
            y = 0,
            x = 0,
            scrollY = 1,
        },
        [10] = {
            visible = true,
            scrollX = 1,
            scaleX = 10.3,
            scaleY = 10.3,
            path = "Pixel_gf",
            type = "sprite",
            y = -29.428571428571,
            x = -17.428571428571,
            scrollY = 1,
        },
        [11] = {
            visible = true,
            scrollX = 1,
            scaleX = 9,
            scaleY = 9,
            path = "BF",
            type = "sprite",
            y = 178.71428571429,
            x = 223.92857142857,
            scrollY = 1,
        },
        [12] = {
            visible = true,
            scrollX = 1,
            scaleX = 11,
            scaleY = 11,
            path = "Sonic_EXE_Pixel",
            type = "sprite",
            y = 90.285714285714,
            x = -248.28571428571,
            scrollY = 1,
        },
    },
}