return {
    marks = {
        [1] = {
            x = 0,
            y = 0,
            name = "BF",
            color = {
                [1] = 0,
                [2] = 1,
                [3] = 0,
            },
        },
        [2] = {
            x = 0,
            y = 0,
            name = "GF",
            color = {
                [1] = 1,
                [2] = 0,
                [3] = 1,
            },
        },
        [3] = {
            x = 0,
            y = 0,
            name = "Enemy",
            color = {
                [1] = 1,
                [2] = 0,
                [3] = 0,
            },
        },
    },
    layers = {
        [1] = {
            path = "PolishedP1/SKY",
            scrollY = 1,
            type = "image",
            visible = true,
            x = 0,
            scaleY = 1,
            y = 0,
            scrollX = 1,
            scaleX = 1,
        },
        [2] = {
            path = "PolishedP1/HILLS",
            scrollY = 1,
            type = "image",
            visible = true,
            x = 0,
            scaleY = 1,
            y = 0,
            scrollX = 1,
            scaleX = 1,
        },
        [3] = {
            path = "PolishedP1/FLOOR2",
            scrollY = 1,
            type = "image",
            visible = true,
            x = 0,
            scaleY = 1,
            y = 0,
            scrollX = 1,
            scaleX = 1,
        },
        [4] = {
            path = "PolishedP1/FLOOR1",
            scrollY = 1,
            type = "image",
            visible = true,
            x = 0,
            scaleY = 1,
            y = 0,
            scrollX = 1,
            scaleX = 1,
        },
        [5] = {
            path = "PolishedP1/frontgrass",
            scrollY = 1,
            type = "image",
            visible = true,
            x = 0,
            scaleY = 1,
            y = 0,
            scrollX = 1,
            scaleX = 1,
        },
        [6] = {
            path = "PolishedP1/EGGMAN",
            scrollY = 1,
            type = "image",
            visible = true,
            x = 0,
            scaleY = 1,
            y = 0,
            scrollX = 1,
            scaleX = 1,
        },
        [7] = {
            path = "girlfriend",
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = 65.357142857143,
            scaleY = 1,
            y = -17.142857142857,
            scrollX = 1,
            scaleX = 1,
        },
        [8] = {
            path = "boyfriend",
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = 321.90476190476,
            scaleY = 1,
            y = 195.64285714286,
            scrollX = 1,
            scaleX = 1,
        },
        [9] = {
            path = "PolishedP1/KNUCKLE",
            scrollY = 1,
            type = "image",
            visible = true,
            x = 282,
            scaleY = 1,
            y = -116,
            scrollX = 1,
            scaleX = 1,
        },
        [10] = {
            path = "PolishedP1/TAIL",
            scrollY = 1,
            type = "image",
            visible = true,
            x = -142.5,
            scaleY = 1,
            y = -17.5,
            scrollX = 1,
            scaleX = 1,
        },
        [11] = {
            path = "PolishedP1/TailsSpikeAnimated",
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -674.1,
            scaleY = 1.1,
            y = -11.7,
            scrollX = 1,
            scaleX = 1.1,
        },
        [12] = {
            path = "Sonic_EXE_Assets",
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -319.28571428571,
            scaleY = 1,
            y = 107.38095238096,
            scrollX = 1,
            scaleX = 1,
        },
    },
}