return {
    layers = {
        {
            path = "png/weekend1/phillyStreets/phillySkybox",
            scaleX = 1.1,
            scaleY = 1.1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = -36.666666666667,
            y = -606.66666666667,
        },
        {
            path = "png/weekend1/phillyStreets/phillySkyline",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = -30,
            y = -310,
        },
        {
            path = "png/weekend1/phillyStreets/phillyForegroundCity",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = 203.33333333333,
            y = -186.66666666667,
        },
        {
            path = "png/weekend1/phillyStreets/phillyHighwayLights",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = -698,
            y = -563.33333333333,
        },
        {
            path = "png/weekend1/phillyStreets/phillyHighway",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = -496.66666666667,
            y = -423.33333333333,
        },
        {
            path = "png/weekend1/phillyStreets/phillyHighwayLights_lightmap",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            blend = "add",
            alpha = 0.6,
            x = -697,
            y = -564,
        },
        {
            path = "png/weekend1/phillyStreets/phillyConstruction",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = 916.66666666667,
            y = -206.66666666667,
        },
        {
            path = "png/weekend1/phillyStreets/phillySmog",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = -26.666666666667,
            y = -156.66666666667,
        },
        {
            path = "weekend1/phillyCars2",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = 1625.8333333333,
            y = 30,
        },
        {
            path = "weekend1/phillyCars",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -14.888888888892,
            y = -29.333333333333,
        },
        {
            path = "weekend1/phillyTraffic",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = 610,
            y = -120,
        },
        {
            path = "png/weekend1/phillyStreets/phillyTraffic_lightmap",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            blend = "add",
            alpha = 0.6,
            x = 610.85714285714,
            y = -119.85714285714,
        },
        {
            path = "png/weekend1/phillyStreets/phillyForeground",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = 0,
            y = 0,
        },
        {
            path = "png/weekend1/char/superUsefullImage",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = -280.33333333333,
            y = 34,
        },
        {
            path = "weekend1/AbotAis",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -307.81920594325,
            y = 33.603641456583,
        },
        {
            path = "weekend1/AbotSystem",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -6.333333333333,
            y = -47.666666666667,
        },
        {
            path = "weekend1/Nene",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -41.333333333333,
            y = -294.33333333333,
        },
        {
            path = "weekend1/darnell",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = -566.66666666667,
            y = 23.333333333333,
        },
        {
            path = "png/weekend1/SpraycanPile",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = -453.33333333333,
            y = 193.33333333333,
        },
        {
            path = "weekend1/Pico_FNF_assetss",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "sprite",
            visible = true,
            x = 620,
            y = 35,
        },
        {
            path = "png/nastyObject3",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = 14.666666666667,
            y = -203.33333333333,
        },
        {
            path = "png/nastyObject",
            scaleX = 1,
            scaleY = 1,
            scrollX = 1,
            scrollY = 1,
            type = "image",
            visible = true,
            x = 372,
            y = 10,
        },
    },
    marks = {
        {
            color = {
                0,
                1,
                0,
            },
            name = "BF",
            x = 0,
            y = 0,
        },
        {
            color = {
                1,
                0,
                1,
            },
            name = "GF",
            x = 0,
            y = 0,
        },
        {
            color = {
                1,
                0,
                0,
            },
            name = "Enemy",
            x = 0,
            y = 0,
        },
    },
}