return {
    marks = {
        [1] = {
            x = 0,
            y = 0,
            color = {
                [1] = 0,
                [2] = 1,
                [3] = 0,
            },
            name = "BF",
        },
        [2] = {
            x = 0,
            y = 0,
            color = {
                [1] = 1,
                [2] = 0,
                [3] = 1,
            },
            name = "GF",
        },
        [3] = {
            x = 0,
            y = 0,
            color = {
                [1] = 1,
                [2] = 0,
                [3] = 0,
            },
            name = "Enemy",
        },
    },
    layers = {
        [1] = {
            scrollX = 1,
            scrollY = 1,
            x = 0,
            path = "menuYellow",
            scaleY = 1,
            visible = true,
            type = "image",
            y = 0,
            scaleX = 1,
        },
        [2] = {
            scrollX = 1,
            scrollY = 1,
            x = 0,
            path = "black",
            scaleY = 1,
            visible = true,
            type = "image",
            y = 0,
            scaleX = 1,
        },
        [3] = {
            scrollX = 1,
            scrollY = 1,
            x = 0,
            path = "storymenu/props/Menu_BF",
            scaleY = 1,
            visible = true,
            type = "sprite",
            y = -92.690476190476,
            scaleX = 1,
        },
        [4] = {
            scrollX = 1,
            scrollY = 1,
            x = 440,
            path = "storymenu/props/Menu_GF",
            scaleY = 0.9,
            visible = true,
            type = "sprite",
            y = -84.83333333333,
            scaleX = 0.9,
        },
        [5] = {
            scrollX = 1,
            scrollY = 1,
            x = -449.16666666667,
            path = "storymenu/props/Menu_Dad",
            scaleY = 1,
            visible = true,
            type = "sprite",
            y = -116.16666666667,
            scaleX = 1,
        },
        [6] = {
            scrollX = 1,
            scrollY = 1,
            x = 608,
            path = "storymenu/ui/arrows",
            scaleY = 1,
            visible = true,
            type = "sprite",
            y = 176.5,
            scaleX = 1,
        },
        [7] = {
            scrollX = 1,
            scrollY = 1,
            x = 426.41666666667,
            path = "storymenu/difficulties/normal",
            scaleY = 1,
            visible = true,
            type = "image",
            y = 177.09523809524,
            scaleX = 1,
        },
        [8] = {
            scrollX = 1,
            scrollY = 1,
            x = 245.5,
            path = "storymenu/ui/arrows",
            scaleY = 1,
            visible = true,
            type = "sprite",
            y = 176.5,
            scaleX = 1,
        },
        [9] = {
            scrollX = 1,
            scrollY = 1,
            x = 1.6666666666667,
            path = "storymenu/titles/week1",
            scaleY = 1,
            visible = true,
            type = "image",
            y = 171.66666666667,
            scaleX = 1,
        },
    },
}